import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Breadcrumbs from "@/components/Breadcrumbs";
// import CategoriesMenu from "@/components/CategoriesMenu";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Navbar />
        <main className="pt-[4rem]"> 
          <Breadcrumbs />
         
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}