// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Breadcrumbs from "@/components/Breadcrumbs";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Navbar />
        <Breadcrumbs />
        <main className="flex-1 w-full px-4 sm:px-6 lg:px-8 pt-28 max-w-7xl mx-auto"> 
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}